# Generated by Django 5.2.10 on 2026-02-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("power", "Power"),
                            ("water", "Water"),
                            ("gas", "Gas"),
                            ("internet", "Internet"),
                            ("trash", "Trash"),
                            ("hoa", "HOA"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(max_length=160)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "account_number_hint",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilities",
                        to="portal.transaction",
                    ),
                ),
            ],
        ),
    ]
