# Generated by Django 5.2.10 on 2026-02-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="hero_image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
