# Generated by Django 5.2.10 on 2026-02-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_document_hero_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="hero_image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
