# Generated by Django 5.2.10 on 2026-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_transaction_hero_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="photo_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
