# Generated by Django 5.2.10 on 2026-02-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_agent_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="brokerage_logo_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
