# Generated by Django 5.2.10 on 2026-02-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_agent_brokerage_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="homestead_exemption_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="transaction",
            name="review_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="AgentFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=220)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="portal.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("closing_attorney", "Closing Attorney"),
                            ("inspector", "Inspector"),
                            ("lender", "Lender"),
                            ("insurance", "Insurance"),
                            ("title", "Title/Closing"),
                            ("mover", "Mover"),
                            ("handyman", "Handyman"),
                            ("cleaner", "Cleaner"),
                            ("utility", "Utility"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("is_favorite", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="portal.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("closing_attorney", "Closing Attorney"),
                            ("preferred_vendor", "Preferred Vendor"),
                            ("utility", "Utility"),
                        ],
                        default="preferred_vendor",
                        max_length=40,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes_override", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_vendors",
                        to="portal.transaction",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_links",
                        to="portal.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("transaction", "vendor", "role")},
            },
        ),
    ]
