# Generated by Django 5.2.10 on 2026-02-05 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_agentportaltoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="hero_image_url",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
    ]
