# Generated by Django 5.2.10 on 2026-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_rename_hero_image_url_document_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="my_documents_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
