# Generated by Django 5.2.10 on 2026-02-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0012_transaction_my_documents_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(default="My Documents", max_length=200),
        ),
    ]
